CONTIKI = ../..

#cpms: cpms.o channel-scan.o
#	cc -o cpms cpms.o channel-scan.o

#cpms.o: cpms.c channel-scan.h
#	cc -c cpms.c

#channel-scan.o: channel-scan.c channel-scan.h
#	cc -c channel-scan.c

#clean:
#	rm cpms cpms.o channel-scan.o

all: cpms

CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
