CONTIKI = ../..

all: example-abc example-mesh example-collect example-trickle example-polite \
     example-runicast example-unicast example-neighbors example-broadcast

CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
